# PostgreSQL configuration for InsForge
# Enable logical replication for Logflare

# Listen on all interfaces to allow container connections
listen_addresses = '*'

# Set WAL level to logical for Logflare replication
wal_level = logical

# Set max replication slots (needed for logical replication)
max_replication_slots = 10

# Set max WAL senders
max_wal_senders = 10

# Shared preload libraries
shared_preload_libraries = 'pg_cron,http,pgcrypto,insforge_pg_utils'

insforge.policy_grant_role = 'project_admin'
insforge.policy_grant_tables = 'storage.objects,realtime.channels,realtime.messages,payments.checkout_sessions,payments.customer_portal_sessions'

cron.database_name = 'insforge' # Add this line to specify the database for pg_cron
